### ISSUE TITLE
formBuilder.actions.getData() is not working

### ISSUE THREAD

**Issue by thilini1986** [kevinchappell/formBuilder#462] opened 2017-05-17 08:35 UTC
formBuilder.actions.getData() is not working with new update

     http://formbuilder.readthedocs.io/en/latest/formBuilder/actions/getData/

    form-builder.js?779f:1427 Uncaught TypeError: Cannot read property 'prepData' of undefined
    at Object.json (eval at <anonymous> (form-builder.js:436), <anonymous>:1338:41)
    at Object.getData (eval at <anonymous> (form-builder.js:436), <anonymous>:1342:24)
    at HTMLButtonElement.<anonymous> (pen.js:10)

**Comment by kevinchappell** [comment] 2017-05-17 12:14
Resolved in #463

**Closed by kevinchappell** 2017-05-17 12:14 UTC

**Comment by ziarno** [comment] 2017-05-19 13:02
this fix does not seem to be on npm - when I search for `getFormData` in `dist/form-builder.js` it doesn't find anything

**Comment by meysampg** [comment] 2017-05-23 09:11
I downloaded the last version from github, but similar to the first post of this issue, error will be appear for me!

```
form-builder.js?779f:1427 Uncaught TypeError: Cannot read property 'prepData' of undefined
    at Object.json (eval at <anonymous> (form-builder.js:436), <anonymous>:1338:41)
    at Object.getData (eval at <anonymous> (form-builder.js:436), <anonymous>:1342:24)
    at Object.get formData [as formData] (eval at <anonymous> (form-builder.js:436), <anonymous>:1410:33)
    at HTMLFormElement.<anonymous> (create:834)
    at HTMLFormElement.dispatch (jquery.js:4737)
    at HTMLFormElement.elemData.handle (jquery.js:4549)
```
Can it be related to version of jQuery? I use jQuery v2.4 and as I see ib project `bower.json` file the minimum required version is 3.1.

**Comment by kevinchappell** [comment] 2017-05-23 10:36
@meysampg I did not see where `getData` was being called in [yii2-formBuilder](https://github.com/meysampg/yii2-formbuilder) otherwise I would submit PR to fix. This should only be an issue when getData is called before formBuilder is fully initialized. I'm updating the documentation now to be more clear.

**Comment by grierson** [comment] 2017-05-23 14:20
@meysampg 
I'm using JQuery 3.2.1 and getting the same issue.

**Comment by kevinchappell** [comment] 2017-05-23 14:24
Sorry guys, I'm flying blind here. Can someone create a jsfiddle that replicates the issue?
Also be sure to [check out the docs](http://formbuilder.readthedocs.io/en/latest/formBuilder/actions/getData/) from `actions.getData` they were updated today to address this issue.

**Comment by grierson** [comment] 2017-05-23 14:27
Hey,

I just tried it again with the .min.js version worked.
The .js file on Github/Bower is still 2.1.2 from the comment at the top of the file.

**Comment by kevinchappell** [comment] 2017-05-23 14:33
I see, that clarifies things. The unminifed version will no longer be served as its pretty uneditable anyways. Will remove .js version and see about updating bower, though bower team themselves suggests switching to yarn.

**Comment by meysampg** [comment] 2017-05-24 06:16
@kevinchappell It's not used directly in [yii2-formbuilder](https://github.com/meysampg/yii2-formbuilder) (And thanks For idea! I will try for emerge it! :wink:). I tried to use it on front-end layer of my application and it threw the mentioned error. For solving this problem, as you said, I tried to install package with yarn and by using `v2.2.6` now the problem is solved.

**Comment by parthik-quebix** [comment] 2022-02-18 04:29
demoFirst.js:263 Uncaught TypeError: fb.actions.getData is not a function
    at demoFirst.js:263:35
    at Array.map (<anonymous>)
    at HTMLButtonElement.<anonymous> (demoFirst.js:262:37)
    at HTMLButtonElement.dispatch (vendor.js:5206:27)
    at HTMLButtonElement.elemData.handle (vendor.js:5014:28)
