### ISSUE TITLE
Any chance of conditions ported from formeo?

### ISSUE THREAD

**Issue by stcbus** [kevinchappell/formBuilder#1365] opened 2023-03-06 03:15 UTC
### Description:

Any chance we could get conditions ported from the formeo project? This one seems like it’s more maintained? Otherwise this project is perfect for me to be able to offer some great form customization in a general sense without custom building for each customer.

**Comment by lucasnetau** [comment] 2023-09-11 00:17
Until this is supported within formBuilder, you can try out this plugin https://github.com/rendezz/formbuilder_depends 

Duplicate of https://github.com/kevinchappell/formBuilder/issues/478

**Comment by stcbus** [comment] 2023-09-11 00:28
Hey thanks!–SteveOn Sep 10, 2023, at 8:18 PM, James Lucas ***@***.***> wrote:﻿
Until this is supported within formBuilder, you can try out this plugin https://github.com/rendezz/formbuilder_depends
Duplicate of #478

**Comment by lucasnetau** [comment] 2023-12-21 21:27
Closing as duplicate of https://github.com/kevinchappell/formBuilder/issues/478

**Closed by lucasnetau** 2023-12-21 21:27 UTC
Labels: enhancement
