### ISSUE TITLE
same class name problem ("form-group")

### ISSUE THREAD

**Issue by ug-code** [kevinchappell/formBuilder#727] opened 2018-03-16 07:33 UTC
Hi kevinchappell,

Sorry for my english 
my english is very bad : )

your javascript file is not custom for my theme [metronic](https://keenthemes.com/metronic/preview/?demo=default)

for example 
my theme css use  this class name  (form-group)
``<div class="form-group"> bla bla</div> ``

and you javascript file is as follows (form-builder.min.js)
``
.form-elements, .form-group, .multi-row span, textarea {
    display: block; 
}
``

you have to add custom name  
for example 
``
.fb-form-elements, .fb-form-group, .fb-multi-row span, fb.textarea {
    display: block; 
}
``
or
``
.fb.form-elements, .fb.form-group, .fb.multi-row span, fb.textarea {
    display: block; 
}
``

**Comment by bretto36** [comment] 2021-02-05 22:23
This is still present and an issue. In bootstrap 4 form-group is by default display:flex but this class forces it to be display block. 

Can we simple add a prefix to the class names

`.form-builder .form-elements, .form-builder .form-group, .form-builder .multi-row span, .form-builder textarea { display: block; }`

**Comment by dainw** [comment] 2022-05-02 17:31
Including formBuilder on a bootstrap page results in all form-group elements being broken with display:block. As an example, the button on this form should be attached to the right side of the search box:

![image](https://user-images.githubusercontent.com/6842359/166292015-61933c07-00d5-4ae0-ae78-76a0db143a55.png)

It looks like [form-builder.scss](https://github.com/kevinchappell/formBuilder/blob/master/src/sass/form-builder.scss) might be closing the .form-wrap.form-builder block early. Please reference @sophanox [comment](https://github.com/kevinchappell/formBuilder/issues/594#issuecomment-395476193) for a possible solution.

**Comment by lucasnetau** [comment] 2023-09-11 04:48
duplicate of https://github.com/kevinchappell/formBuilder/issues/594

**Closed** 2023-10-06 00:02 UTC
Labels: bug
