### ISSUE TITLE
FormBuilder Loses CSS Class Information When Loading XML

### ISSUE THREAD

**Issue by starlightknight** [kevinchappell/formBuilder#531] opened 2017-06-15 18:26 UTC
### Description:
When loading from saved XML, FormBuilder loses any CSS Class Information indicated in the XML. This causes the styling to be incorrect when the form is rendered.

### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: Firefox/Chrome
 - OS: Linux

### Expected Behavior

When loading a form back into formbuilder for further editing, the CSS class info should also be loaded.

### Actual Behavior

All CSS class information is lost, and the form builder has blank populated instead of the default class. Rendering is then messed up because of the loss of information

### Steps to Reproduce

**With Sample Project:**

1) Download sample project: http://www.mediafire.com/file/j2z54uy1ukgiaw6/Form+Builder+Bug+-+CSS+Classes+Lost+On+Load.zip

2) Open builder.js - look at sample XML provided, generated by formbuilder. Classes are set on the element.

3) Open formbuilder.html. The form is loaded, but the class field is now blank

4) Click Log to Console. You'll note that the class info is lost, even if you change nothing and it was on the input xml.

**Manually:**

1) Add an element to the form. Set one or more classes

2) Save to XML

3) Load it again into a new formbuilder. Observe information is lost.

**Comment by thatSchloesser** [comment] 2017-07-25 14:46
+1

See example of issue here: https://codepen.io/anon/pen/vJEZYV

**Comment by cklone** [comment] 2017-08-17 23:48
+1

Looks like ``formBuilder.actions.getData('xml')`` gives you ``class="form-control"`` instead of ``className="form-control"`` like JSON does.

**Comment by Jojoshua** [comment] 2022-03-16 04:47
> ### Description:
> When loading from saved XML, FormBuilder loses any CSS Class Information indicated in the XML. This causes the styling to be incorrect when the form is rendered.
> 
> ### Environment Details:
> 
>  - formBuilder Version: 2.5.3
>  - Browser: Firefox/Chrome
>  - OS: Linux
> 
> ### Expected Behavior
> 
> When loading a form back into formbuilder for further editing, the CSS class info should also be loaded.
> 
> ### Actual Behavior
> 
> All CSS class information is lost, and the form builder has blank populated instead of the default class. Rendering is then messed up because of the loss of information
> 
> ### Steps to Reproduce
> 
> **With Sample Project:**
> 
> 1) Download sample project: http://www.mediafire.com/file/j2z54uy1ukgiaw6/Form+Builder+Bug+-+CSS+Classes+Lost+On+Load.zip
> 
> 2) Open builder.js - look at sample XML provided, generated by formbuilder. Classes are set on the element.
> 
> 3) Open formbuilder.html. The form is loaded, but the class field is now blank
> 
> 4) Click Log to Console. You'll note that the class info is lost, even if you change nothing and it was on the input xml.
> 
> **Manually:**
> 
> 1) Add an element to the form. Set one or more classes
> 
> 2) Save to XML
> 
> 3) Load it again into a new formbuilder. Observe information is lost.
> 

If this is still an issue can you post a fiddle?

**Comment by lucasnetau** [comment] 2023-10-05 07:40
I do not believe this is still an issue, it has likely been fixed in a later version

`formBuilder.actions.getData('xml')` exports with class-name correctly. Loading this loads the class value

```xml
<form-template xmlns="http://www.w3.org/1999/xhtml">
  <fields>
    <field type="header" subtype="h1" label="Header" class-name="my-class"></field>
  </fields>
</form-template>
```

Please re-open if this still occurs and provide a reproduction script.

**Closed by lucasnetau** 2023-10-05 07:40 UTC
Labels: bug
