### ISSUE TITLE
Can't edit Label on any input field

### ISSUE THREAD

**Issue by davidbaselj** [kevinchappell/formBuilder#1273] opened 2022-03-17 10:04 UTC
### Description:

I have tested new version and and I cant edit Labels. As I was checking HTML code and comparing it to previous version I saw diference in `contenteditable`.

> Edit:
> Setting `disableHTMLLabels: true` removes the issue.
> 

Previous version:
`contenteditable="true"`

Version 3.8.0:
`contenteditable="contenteditable"`

If I manually change `contenteditable` to `true` than it works.

Is this bug or there is something wrong with configuration 🤔 ? 

![image](https://user-images.githubusercontent.com/7064170/158784866-5f9d461a-169c-436f-b2fb-fe5b0950afcf.png)

### Environment Details:

 - formBuilder Version: 3.8.0
 - Browser: Chrome
 - OS: Windows

### Expected Behavior
Change text in `Label`
### Actual Behavior
Can't edit Label

### Steps to Reproduce
Test latest version 3.8.0

**Comment by kevinchappell** [comment] 2022-03-17 19:51
@davidbaselj will look into this. thanks for reporting.

**Comment by Jojoshua** [comment] 2022-03-17 20:46
> @davidbaselj, will look into this. thanks for reporting.

This is duplicate of https://github.com/kevinchappell/formBuilder/issues/1251.

This actually broke in 3.7.4. I highlighted where I think the issue is in the comment

**Comment by Jojoshua** [comment] 2022-03-18 21:26
Fixed in latest release

**Closed by Jojoshua** 2022-03-18 21:26 UTC
Labels: bug, pending-fix

**Comment by davidh07** [comment] 2022-03-19 13:41
When will the latest release be published to 
https://formbuilder.online/assets/js/form-builder.min.js
Thank you!

**Comment by davidh07** [comment] 2022-03-19 13:42
Also, is there a way to setup versioning on these files like jquery so:
https://formbuilder.online/assets/js/form-builder.3.8.0.min.js
