### ISSUE TITLE
When using parentheses in Help Text an error is thrown

### ISSUE THREAD

**Issue by MaxShv** [kevinchappell/formBuilder#573] opened 2017-08-04 21:45 UTC
### Description:
 Error is thrown when using parentheses in Help Text field

### Environment Details: 
 - formBuilder Version: 2.5.3
 - Electron version 1.6.8
 - OS: Mac

### Steps to Reproduce
Edit checkbox group and add help text with parentheses

![image](https://user-images.githubusercontent.com/6601478/28988090-4170d5c0-793c-11e7-8669-8d8bac7f6eef.png)

**Comment by dema121** [comment] 2017-08-07 15:29
It's browser related.
No problem in Chrome, same error in IE11.

**Comment by kevinchappell** [comment] 2017-08-15 15:54
Pretty sure I know what this is but will need to look closer. You can start by logging what `label` is here: https://github.com/kevinchappell/formBuilder/blob/master/src/js/layout.js#L26

checkbox group labels work differently than other fields so may not have the `append()` method

**Comment by kevinchappell** [comment] 2017-09-03 13:48
I think this was resolved in 2.9.3, as the issue is no longer reproducable. please reopen if problem continues

**Closed by kevinchappell** 2017-09-03 13:48 UTC
