### ISSUE TITLE
Tabs - push 

### ISSUE THREAD

**Issue by simon1982** [kevinchappell/formBuilder#1161] opened 2021-02-16 11:47 UTC
### Description:
Loading JSON data for the form in multipage/tabs way.

I have proper JSON from DB via XMLHttpRequest

Via for loop the new tabs are created and field with formBuild, this works. 

So on the web page all look ok, while in the **fbInstances** each new instance overwrites the existing one, so all data cannot be retrieved.

### Environment Details:

 - formBuilder Version: 3.6.2
 - Browser: Safari
 - OS: macOS Big Sur 11.2

### Expected Behavior

**fbInstances**  will hold all data from the DB JSON that has been push an from the add new tab action. 

### Actual Behavior
push() **fbInstances** overwrites the existing, so event with 10 instance aka tabs there is only 1 object in **fbinstance**
### Steps to Reproduce

Apply below code it would required some JSON with tow arrays for tow tabs 

### Screenshot - *(optional)*
`jQuery(($) => {
    "use strict";
    var $fbPages = $(document.getElementById("form-builder-pages"));
    var addPageTab = document.getElementById("btn-add-tab");
    var fbInstances = [];
    var request = new XMLHttpRequest();
    var uid = window.location.pathname.split('/').reverse()[1];
    request.open('GET', '/api/' + uid, true);
    request.send(null);
    request.onreadystatechange = function() {
        if (request.readyState === 4 && request.status === 200) {
            var type = request.getResponseHeader('Content-Type');
            var result = request.responseText;
            var res = JSON.parse(result);
            console.log(res.length);
            var tabCount = 1;
            var status = 'active';
            if (res.length != 0) {
                for (var i = 1; i <= res.length; i++) {
                    console.log(i)
                    console.log(res[i - 1]);
                    var countFB = i;
                    var tabCount = countFB;
                    var final_tab_id = countFB;
                    var tabId = "#page-" + countFB.toString();
                    var aria = "page-" + countFB.toString();
                    const $newPageTemplate = document.getElementById("new-page");
                    const $newTabTemplate = document.getElementById("add-page-tab");
                    const $newPage = $newPageTemplate.cloneNode(true);
                    var fields = [{
                        type: "radio-group",
                        label: "Scale 1",
                        inline: true,
                        values: [{
                                label: "Extremely satisfied",
                                value: "Extremely satisfied",
                            },
                            {
                                label: "Very satisfied",
                                value: "Very satisfied",
                            },
                            {
                                label: "Less satisfied",
                                value: "Less satisfied",
                            },
                            {
                                label: "Dissatisfied",
                                value: "Dissatisfied",
                            }
                        ]
                    }];
                    var optionsLoop = {
                        formData: res[i - 1],
                        disableFields: ['autocomplete', 'hidden', 'file', 'paragraph'],
                        showActionButtons: false,
                        onClearAll: () => window.sessionStorage.removeItem('formData'),
                        stickyControls: {
                            enable: false
                        },
                        fields: fields,
                        sortableControls: true,
                        controlPosition: 'right',
                    };

                    $newPage.setAttribute("id", aria);

                    $newPage.classList.add("fb-editor");

                    const $newTab = $newTabTemplate.cloneNode(true);
                    $newTab.removeAttribute("id");
                    const $tabLink = $newTab.querySelector("a");
                    $tabLink.setAttribute("href", tabId);
                    $tabLink.setAttribute("aria-controls", aria);

                    $tabLink.innerText = "Page " + tabCount;
                    if (i > 1) {
                        $tabLink.classList.add('active');
                        $newPage.classList.add('active');
                    }
                    $newPageTemplate.parentElement.insertBefore($newPage, $newPageTemplate);
                    $newTabTemplate.parentElement.insertBefore($newTab, $newTabTemplate);
                    fbInstances.push($($newPage).formBuilder(optionsLoop));

                }

                

            } else {
                alert('No data')
            }
        }
    }

    addPageTab.addEventListener(
        "click",
        (click) => {
            const tabCount = document.getElementById("tabs").children.length;
            console.log('add button count: ' + tabCount)
            const tabId = "#page-" + tabCount.toString();
            var aria = "page-" + tabCount.toString();
            const $newPageTemplate = document.getElementById("new-page");
            const $newTabTemplate = document.getElementById("add-page-tab");
            const $newPage = $newPageTemplate.cloneNode(true);
            $newPage.setAttribute("id", aria);
            $newPage.classList.add("fb-editor");
            const $newTab = $newTabTemplate.cloneNode(true);
            $newTab.removeAttribute("id");
            const $tabLink = $newTab.querySelector("a");
            $tabLink.setAttribute("href", tabId);
            $tabLink.innerText = "Page " + tabCount;
            $newPageTemplate.parentElement.insertBefore($newPage, $newPageTemplate);
            $newTabTemplate.parentElement.insertBefore($newTab, $newTabTemplate);
            fbInstances.push($($newPage).formBuilder());
        },
        false
    );

    fbInstances.push($(".fb-editor").formBuilder());
    console.log(fbInstances);

    $(document.getElementById("save-all")).click(function() {
        const allData = fbInstances.map((fb) => {
            console.log(fb);
            console.log(fb.actions.getData());
            return fb.formData;
        });
        console.log(allData);
    });
});`

**Comment by simon1982** [comment] 2021-02-16 13:15
![Zrzut ekranu 2021-02-16 o 14 14 28](https://user-images.githubusercontent.com/9418372/108067607-53807c00-7061-11eb-84f4-6618c895b0b4.png)

It's look like on your page : https://formbuilder.online/docs/formBuilder/demos/tabs/  there is the same issue :(

**Comment by filtenorio** [comment] 2021-09-02 06:41
Hi Simon,

I was having the same trouble as you. The problem is that when you loop through jQuery it pushes the array before the formbuilder renders, causing the array to clone the data from the last instance.

The solution is to use a recursive function with promises, so the array push will only occur when the function is finished.

Use this as an example: https://codepen.io/chiahungwang/pen/PoYrMEZ?editors=1010

Good luck!

**Comment by Jojoshua** [comment] 2022-03-19 03:23
Looks like this has a good solution above, closing.

**Closed by Jojoshua** 2022-03-19 03:23 UTC
