### ISSUE TITLE
Closeallfeildedit not working

### ISSUE THREAD

**Issue by vinokumark** [kevinchappell/formBuilder#1455] opened 2023-10-18 17:36 UTC
jQuery.Deferred exception: formBuilder.actions.closeAllFieldEdit is not a function TypeError: formBuilder.actions.closeAllFieldEdit is not a function

How to disable the all field while render the data

**Comment by lucasnetau** [comment] 2023-10-18 22:36
Please provide a full reproduction script for your issue. I cannot replicate your issue locally, closeAllFieldEdit is defined. It would suggest that your formBuilder instance has not been initialised correctly

**Comment by vinokumark** [comment] 2023-10-19 02:24
Can you provide example of closeAllFieldEdit in codepen.

**Comment by lucasnetau** [comment] 2023-10-19 02:36
https://formbuilder.online/docs/formBuilder/actions/closeAllFieldEdit/

**Comment by vinokumark** [comment] 2023-10-19 02:43
The given doc link does not have a codepen example.

[image: image.png]

**Comment by lucasnetau** [comment] 2023-10-19 02:47
formBuilder.actions.closeAllFieldEdit() is a single action call which will closes all edit fields on the stage. The documentation link provided includes all javascript required in the example.

**Comment by vinokumark** [comment] 2023-10-19 03:30
Please see this

https://codepen.io/kvinoth69/pen/wvRVEyR

**Comment by lucasnetau** [comment] 2023-10-19 05:59
This is wrong in the codepen

`$(fbEditor).formBuilder.actions.closeAllFieldEdit()`

should be 

`formBuilder.actions.closeAllFieldEdit()`

However the issue is what I mentioned in my first response. formBuilder isn't initialised at the time you call closeAllFieldEdit. I'm unsure why you are wanting to call it straight away since you don't have any edit panels open after loading the form, however if you do want to call it you need to wait for formBuilder to initialise first. The simplest way to do that is to use the promise function

https://formbuilder.online/docs/formBuilder/promise/

Normally you would be calling closeAllFieldEdit() from some piece of code in reaction to say clicking a button.

**Comment by lucasnetau** [comment] 2023-10-20 03:47
While not solving you issue, PR #https://github.com/kevinchappell/formBuilder/pull/1459 landed which will emit an error if you try to call a function prior to formBuilder being initialised

**Comment by lucasnetau** [comment] 2023-10-24 00:25
Feedback provided and additional error reporting make to formBuilder to highlight trying to execute actions before initialisation is complete

**Closed by lucasnetau** 2023-10-24 00:25 UTC
