### ISSUE TITLE
Delete input groups at one time

### ISSUE THREAD

**Issue by roshanjha12** [kevinchappell/formBuilder#576] opened 2017-08-11 09:16 UTC
### Description:
Hi,
I want to delete inputsets at one not each input one by one. any method ?
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by kevinchappell** [comment] 2017-08-27 01:05
This would be a good feature but would require significant refactoring. Adding to backlog

**Comment by lucasnetau** [comment] 2023-10-25 22:59
Adding as duplicate of #627, deletion of input sets would require some form of grouping

**Closed by lucasnetau** 2023-10-25 22:59 UTC
Labels: Feature
