### ISSUE TITLE
Translation support for generated / built forms

### ISSUE THREAD

**Issue by Xsmael** [kevinchappell/formBuilder#879] opened 2018-12-04 14:28 UTC
### Description:
Hello, is it possible to create forms with support for several languages ?
It is already great that we can use the formBuilder in different languages, but how about going further and making it possible that the built form could support several languages. 
Ofcourse, the one creating the form will specify the supported languages and provide translation,

How can i perform that?  is it yet possible ?

Other points are not relevent to this so I removed them.

**Comment by lucasnetau** [comment] 2023-10-26 00:43
Duplicate of #335

**Closed by lucasnetau** 2023-10-26 00:43 UTC
Labels: enhancement, language
