### ISSUE TITLE
InputSets groups

### ISSUE THREAD

**Issue by RickWeb100** [kevinchappell/formBuilder#778] opened 2018-07-18 11:54 UTC
I need the InputSets to drag as a group and to stop users being able to add other form elements within the inputset groups

Is this possible?

**Comment by kevinchappell** [comment] 2018-07-26 15:41
Not currently but would be a nice addition.

**Comment by Nopraz** [comment] 2020-05-05 13:29
Hello @kevinchappell do you have any news on this enhancement ?

**Comment by lucasnetau** [comment] 2023-10-25 22:58
Duplicate of #627

**Closed by lucasnetau** 2023-10-25 22:58 UTC
Labels: enhancement
