### ISSUE TITLE
Remove <br> from required checkbox and radio group labels

### ISSUE THREAD

**Issue by eradin** [kevinchappell/formBuilder#849] opened 2018-11-01 23:55 UTC
2.10.0

In the designer, if the group checkbox (or radio) is required, the red asterisk is presented at the end of the label (correct and consistent with all others).  Under renderer, a <br> is inserted which pushes the asterisk to the next line.  It looks out of place.

**Comment by kevinchappell** [comment] 2018-11-02 00:10
@eradin Can you share a screenshot? I'm not able to reproduce this issue. Also there shouldn't be any `<br/>` rendered from the editor. Could you screenshot where it appears in the code?

![image](https://user-images.githubusercontent.com/1457540/47886675-bd28dd80-ddf8-11e8-819c-c5fba17f2138.png)

**Comment by eradin** [comment] 2018-11-02 00:35
The editor is fine (I called it the designer above).  At render time it's there.  And it no longer appears in the rendered radio-group, just the checkboxes. Markup and scrennshot.

<label for="checkbox-group-1516861794817" class="fb-checkbox-group-label">I agree to notify the Director if my team is not able to participate.<br><span class="fb-required">*</span>

![screenshot_2018-11-02 teamscoring com](https://user-images.githubusercontent.com/3924103/47887411-763ce700-ddfc-11e8-8b49-d4d36a268869.png)

</label>
<div class="checkbox-group"><div class="fb-checkbox"><input name="checkbox-group-1516861794817[]" data-level="fb-indent-l1" id="checkbox-group-1516861794817-0" required="required" aria-required="true" value="1" type="checkbox">
<label for="checkbox-group-1516861794817-0">I agree to notify the Director if my team is not able to participate.
</label>
</div>
<div class="fb-checkbox">
<input name="checkbox-group-1516861794817[]" data-level="fb-indent-l1" id="checkbox-group-1516861794817-1" required="required" aria-required="true" value="1" type="checkbox">
<label for="checkbox-group-1516861794817-1">Option 2</label>
</div>
</div>

**Comment by kevinchappell** [comment] 2018-11-02 03:13
I think somehow a line-break snuck into your label. Labels are contenteditable by default so they support HTML. If you don't need this you can set the `disableHTMLLabels` option to false.

![line-break](https://user-images.githubusercontent.com/1457540/47891923-7647e180-de12-11e8-865d-ae29182750f0.gif)

**Comment by eradin** [comment] 2018-11-02 03:35
I deleted the label and entered it again.  It works now.  I suspect you were right that a \n got in their somehow.  I looked at the saved data and there is no indication it was there.  Strange but it works now.

Thanks

**Comment by kevinchappell** [comment] 2018-11-02 03:39
Sounds like its sorted, closing. :+1:

**Closed by kevinchappell** 2018-11-02 03:39 UTC
