### ISSUE TITLE
Can't used in hosted chromium: Failed to read the 'sessionStorage' property

### ISSUE THREAD

**Issue by DakotaHoosier** [kevinchappell/formBuilder#968] opened 2019-06-21 20:03 UTC
### Environment Details: Win 10, chromium

 - formBuilder Version: 3.2.4
 - Browser: Chrome, 63.0.3239.132
 - OS: Win 10

### Expected Behavior
Basic Example form loads

### Actual Behavior
Error message:
form-builder.min.js:19 DOMException: Failed to read the 'sessionStorage' property from 'Window': Storage is disabled inside 'data:' URLs.
    at e.t.orderFields (https://formbuilder.online/assets/js/form-builder.min.js:19:101889)
    at e.t.appendControls (https://formbuilder.online/assets/js/form-builder.min.js:19:102478)
    at e.t.init (https://formbuilder.online/assets/js/form-builder.min.js:19:100707)
    at new e (https://formbuilder.online/assets/js/form-builder.min.js:19:100631)
    at new A (https://formbuilder.online/assets/js/form-builder.min.js:19:103157)
    at HTMLDivElement.<anonymous> (https://formbuilder.online/assets/js/form-builder.min.js:19:125187)
    at Function.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js:2:2882)
    at n.fn.init.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js:2:847)
    at https://formbuilder.online/assets/js/form-builder.min.js:19:125164
    at <anonymous>

### Steps to Reproduce
I've taken the simplest example that loads fine in Chrome browser on this machine, but when I'm in the hosted chromium control, I get the error in this issue.
I'm using the code in this page to get started: https://kevinchappell.github.io/formBuilder/

**Comment by kevinchappell** [comment] 2019-06-21 22:04
can you share the code used to reproduce this error?

**Comment by DakotaHoosier** [comment] 2019-07-01 20:44
The HTML was https://kevinchappell.github.io/formBuilder/
The issue is how the Chromium component is hosted in that it doesn't provide session/local storage it appears. This is an in-house closed-source app I'm using. I may be able to rig a prototype that would demonstrate the problem. I'm not sure sessionStorage is needed in this case. If not, is there some defensive coding that can catch the exception?

**Comment by kevinchappell** [comment] 2019-07-01 20:59
Can you enable sessionStorage? The only place in formBuilder that doesn't check for sessionStorage is in the demo.js, all other use looks like this. https://github.com/kevinchappell/formBuilder/blob/094573c64d8c14fa5359b8f4d1eff95801c98870/src/js/controls.js#L129

**Comment by lucasnetau** [comment] 2023-08-21 02:51
This was fixed in https://github.com/kevinchappell/formBuilder/pull/1329 and released in version v3.9.0

**Closed** 2023-08-22 10:41 UTC
Labels: bug
