### ISSUE TITLE
Group Control - Super Urgent, please advise. #1552

### ISSUE THREAD

**Issue by rajindersinghugw** [kevinchappell/formBuilder#1553] opened 2024-04-19 11:53 UTC
@lucasnetau  thank you for update.

1) I can not use input set because this is manually process to add element in group section. 
2) i can not see different between single element and group of elements in json format

We need a best drag drop options that will make group of set within container and keep same functionality that we have already exist. 

Let me know if you have method or key that can easy for us to complete this point. Please let me know your thoughts.

Thank you

_Originally posted by @rajindersinghugw in https://github.com/kevinchappell/formBuilder/issues/1552#issuecomment-2066412426_

**Comment by lucasnetau** [comment] 2024-06-04 04:08
Duplicate of #1552

**Closed by lucasnetau** 2024-06-04 04:08 UTC
